_target_: engine.engineCaloATLAS.EngineCaloATLAS
learning_rate: 0.001
n_train_batch_size: 128
n_test_batch_size: 64
n_valid_batch_size: 1024
n_plot_samples: 1
n_batches_log_train: 100
n_epochs: 10
n_gibbs_sampling_steps: 1000
weight_decay_factor: 0.0001
momentum_coefficient: 0.5
run_kl_annealing: 0