_target_: engine.engineAtlasV2.EngineAtlasV2
learning_rate: 0.0001
n_epochs: 150

kl_enabled: 1
ae_enabled: 1
kl_annealing: 1
kl_annealing_ratio: 0.3
kl_gamma_max: 1.0
epoch_annealing_start: 0
annealing_percentage: 0.3
r_param : 0.001

beta_smoothing_fct: 5
beta_smoothing_fct_final: 500
beta_smoothing_fct_anneal: 1

# modelhits: 1
# cl_lambda: 0

slope_activation_fct: 0.05
slope_activation_fct_final: 0.
slope_activation_fct_anneal: 1

n_train_batch_size: 128
n_test_batch_size: 1024
n_valid_batch_size: 1024
rbm_batch_size: 1024

n_gibbs_sampling_steps: 3000

n_val_batches: 3
n_valid_per_epoch: 5

n_plot_samples: 5
n_batches_log_train: 10

val_w_qpu: 0

sample_energies:
  - 1
  - 25
  - 50
  - 100
  - 150