_target_: engine.sample_Calo.Sampling
learning_rate: 0 # In sampling mode, keep the 0 learning rate.
n_batches: 1   # Total sampling number = n_batches * n_valid_batch_size * 10

kl_enabled: 1
ae_enabled: 1
kl_annealing: 1
kl_annealing_ratio: 0.3

n_train_batch_size: 128
n_test_batch_size: 1024
n_valid_batch_size: 1024
rbm_batch_size: 128

n_gibbs_sampling_steps: 1000

n_val_batches: 3
n_valid_per_epoch: 5

n_plot_samples: 5
n_batches_log_train: 10


# The conditional input energy is randomly generated in range (sample_energies[0], sample_energies[1])
sample_energies:
  - 45
  - 60
  

# D-WAVE configurations:

enable_qpu_sampling: 0

constrain_rbm: 0
weight_range: 10
bias_range: 20

init_beta_estimation_iterations: 5
beta_estimation_iterations: 0
beta_estimation_learning_rate: 0.015
