# @package _group_
model_type: DiVAEppCalo
activation_fct: relu
beta_smoothing_fct: 5
decoder_hidden_nodes:
  - 64
  - 128
  - 256
encoder_hidden_nodes:
  - 256
  - 128
  - 64
n_encoder_layer_nodes: 32
n_encoder_layers: 2
n_latent_hierarchy_lvls: 2
n_latent_nodes: 32