
model_type: DiVAEpp
activation_fct: relu
beta_smoothing_fct: 5
decoder_hidden_nodes:
  - 64
  - 64
  - 64
  - 64
n_encoder_layer_nodes: 64
n_encoder_layers: 4
n_latent_hierarchy_lvls: 2
n_latent_nodes: 16