model_type: GumBoltCaloPRBM
activation_fct: relu
beta_smoothing_fct: 5
output_smoothing_fct: 9
decoder_hidden_nodes:
  - 500
  - 450
  - 400
  - 350
  - 300
encoder_hidden_nodes:
  - 400
  - 350
  - 300
  - 250
  - 200
n_latent_hierarchy_lvls: 4
n_latent_nodes: 128