model_type: GumBoltCaloCRBM
activation_fct: relu
beta_smoothing_fct: 5
output_smoothing_fct: 9
decoder_hidden_nodes:
  - 1600
  - 1000
  - 600
encoder_hidden_nodes:
  - 500
  - 400
  - 300
n_latent_hierarchy_lvls: 10
n_latent_nodes: 200

n_encoder_layer_nodes: -1
n_encoder_layers: -1

# Full chip settings
decoder_hidden_nodes:
  - 800
  - 700
  - 600
  - 550  
  - 500
encoder_hidden_nodes:
  - 500
  - 450
  - 400
  - 350
  - 300
n_latent_hierarchy_lvls: 2
n_latent_nodes: 1000

# 2X150 RBM
decoder_hidden_nodes:
  - 300
  - 350
  - 400
  - 450
  - 500
encoder_hidden_nodes:
  - 500
  - 450
  - 400
  - 350
  - 300
n_latent_hierarchy_lvls: 2
n_latent_nodes: 150