model_type: GumBoltAtlasPCRBMCNN
activation_fct: relu
beta_smoothing_fct: 5
output_smoothing_fct: 60
decoder_hidden_nodes:
  - 800
  - 700
  - 600
  - 550  
  - 500
encoder_hidden_nodes:
  - 500
  - 450
  - 400
  - 350
  - 300
n_latent_hierarchy_lvls: 3
n_latent_nodes: 512
# n_latent_nodes: 4096
cylencoding: 0
lz: 1
ltheta: 2
lr: 3
pe: 1
# lz: 45
# ltheta: 16
# lr: 9
# pe: 2
encodertype: Small
#Large, Small, SmallUnconditioned, SmallPosEnc
decodertype: Small
# Small, SmallUnconditioned, SmallPosEnc

fullyconnected: False

alpha: 0.0
gamma: 0.0
mse_weight: 0.5
coefficient: 0.6
interpolation_param: 1.0
bce_weights_power: 0.0
rbmMethod: CD