model_type: GumBoltAtlasPRBMCNN
activation_fct: relu
beta_smoothing_fct: 5
output_smoothing_fct: 60
decoder_hidden_nodes:
  - 800
  - 700
  - 600
  - 550  
  - 500
encoder_hidden_nodes:
  - 500
  - 450
  - 400
  - 350
  - 300
# n_latent_hierarchy_lvls: 4
# n_latent_nodes: 512
#for PB
n_latent_hierarchy_lvls: 4
n_latent_nodes: 512
n_latent_nodes_per_p: 512

cylencoding: 0
# lz: 1
# ltheta: 2
# lr: 3
# pe: 1
lz: 45
ltheta: 16
lr: 9
pe: 2
encodertype: SmallPB
#Large, Small, SmallUnconditioned, SmallPosEnc
decodertype: SmallPB
# Small, SmallUnconditioned, SmallPosEnc, SmallUnconditionedAct, SmallHitsToAct, SmallCharm, SmallUnconditionedHits

encoder_pb_hierarchy: 1

fullyconnected: False
# bernoulli : 0
# alpha: 5.0
# gamma: 5.0
# mse_weight: 0.1
alpha: 0.0
gamma: 0.0
mse_weight: 0.0
interpolation_param: 1.0
bce_weights_power: 0.25
rbmMethod: CD