model_type: GumBoltAtlasPRBMFCN
activation_fct: relu
beta_smoothing_fct: 5
output_smoothing_fct: 60
decoder_hidden_nodes:
  - 800
  - 700
  - 600
  - 550  
  - 500
encoder_hidden_nodes:
  - 500
  - 450
  - 400
  - 350
  - 300
n_latent_hierarchy_lvls: 4
n_latent_nodes: 512
# n_latent_nodes: 4096

fullyconnected: False
# bernoulli : 0
# alpha: 5.0
# gamma: 5.0
# mse_weight: 0.1
alpha: 0.0
gamma: 0.0
mse_weight: 0.0
interpolation_param: 1.0
rbmMethod: CD