model_type: GumBoltAtlasPRBMCNN
activation_fct: relu
beta_smoothing_fct: 5
output_smoothing_fct: 60
decoder_hidden_nodes:
  - 800
  - 700
  - 600
  - 550  
  - 500
encoder_hidden_nodes:
  - 500
  - 450
  - 400
  - 350
  - 300
n_latent_hierarchy_lvls: 1
n_latent_nodes: 2048
# n_latent_nodes: 4096


# bernoulli : 0
# alpha: 5.0
# gamma: 5.0
# mse_weight: 0.1
alpha: 5.0
gamma: 5.0
mse_weight: 1.0
interpolation_param: 0.9
rbmMethod: CD