model_type: GumBoltCaloCRBM
activation_fct: relu
beta_smoothing_fct: 5
output_smoothing_fct: 9
decoder_hidden_nodes:
  - 1600
  - 1000
  - 600
encoder_hidden_nodes:
  - 500
  - 400
  - 300
n_latent_hierarchy_lvls: 10
n_latent_nodes: 200

n_encoder_layer_nodes: -1
n_encoder_layers: -1